namespace PfsenseVoucherMgr
{
    partial class frmShowVoucher
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmShowVoucher));
            this.lblCode = new System.Windows.Forms.Label();
            this.lblToUser = new System.Windows.Forms.Label();
            this.lblFromUser = new System.Windows.Forms.Label();
            this.btnPrint = new System.Windows.Forms.Button();
            this.btnExit = new System.Windows.Forms.Button();
            this.btnPrintPreview = new System.Windows.Forms.Button();
            this.printDocPreviewDialog = new System.Windows.Forms.PrintPreviewDialog();
            this.SuspendLayout();
            // 
            // lblCode
            // 
            this.lblCode.AutoSize = true;
            this.lblCode.Font = new System.Drawing.Font("Microsoft Sans Serif", 12.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblCode.Location = new System.Drawing.Point(72, 68);
            this.lblCode.Name = "lblCode";
            this.lblCode.Size = new System.Drawing.Size(127, 20);
            this.lblCode.TabIndex = 1;
            this.lblCode.Text = "Voucher Code";
            // 
            // lblToUser
            // 
            this.lblToUser.AutoSize = true;
            this.lblToUser.Location = new System.Drawing.Point(12, 18);
            this.lblToUser.Name = "lblToUser";
            this.lblToUser.Size = new System.Drawing.Size(95, 13);
            this.lblToUser.TabIndex = 3;
            this.lblToUser.Text = "Voucher code for :";
            // 
            // lblFromUser
            // 
            this.lblFromUser.AutoSize = true;
            this.lblFromUser.Location = new System.Drawing.Point(12, 128);
            this.lblFromUser.Name = "lblFromUser";
            this.lblFromUser.Size = new System.Drawing.Size(74, 13);
            this.lblFromUser.TabIndex = 4;
            this.lblFromUser.Text = "Generated by:";
            // 
            // btnPrint
            // 
            this.btnPrint.Location = new System.Drawing.Point(40, 162);
            this.btnPrint.Name = "btnPrint";
            this.btnPrint.Size = new System.Drawing.Size(75, 23);
            this.btnPrint.TabIndex = 6;
            this.btnPrint.Text = "Print";
            this.btnPrint.UseVisualStyleBackColor = true;
            this.btnPrint.Click += new System.EventHandler(this.BtnPrint_Click);
            // 
            // btnExit
            // 
            this.btnExit.Location = new System.Drawing.Point(217, 162);
            this.btnExit.Name = "btnExit";
            this.btnExit.Size = new System.Drawing.Size(75, 23);
            this.btnExit.TabIndex = 7;
            this.btnExit.Text = "Exit";
            this.btnExit.UseVisualStyleBackColor = true;
            this.btnExit.Click += new System.EventHandler(this.BtnExit_Click);
            // 
            // btnPrintPreview
            // 
            this.btnPrintPreview.Location = new System.Drawing.Point(121, 162);
            this.btnPrintPreview.Name = "btnPrintPreview";
            this.btnPrintPreview.Size = new System.Drawing.Size(90, 23);
            this.btnPrintPreview.TabIndex = 8;
            this.btnPrintPreview.Text = "Print Preview";
            this.btnPrintPreview.UseVisualStyleBackColor = true;
            this.btnPrintPreview.Click += new System.EventHandler(this.btnPrintPreview_Click);
            // 
            // printDocPreviewDialog
            // 
            this.printDocPreviewDialog.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.printDocPreviewDialog.AutoScrollMinSize = new System.Drawing.Size(0, 0);
            this.printDocPreviewDialog.ClientSize = new System.Drawing.Size(400, 300);
            this.printDocPreviewDialog.Enabled = true;
            this.printDocPreviewDialog.Icon = ((System.Drawing.Icon)(resources.GetObject("printDocPreviewDialog.Icon")));
            this.printDocPreviewDialog.Name = "printDocPreviewDialog";
            this.printDocPreviewDialog.Visible = false;
            // 
            // frmShowVoucher
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(338, 216);
            this.Controls.Add(this.btnPrintPreview);
            this.Controls.Add(this.btnExit);
            this.Controls.Add(this.btnPrint);
            this.Controls.Add(this.lblFromUser);
            this.Controls.Add(this.lblToUser);
            this.Controls.Add(this.lblCode);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "frmShowVoucher";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Show Voucher";
            this.Load += new System.EventHandler(this.frmShowVoucher_Load);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private System.Windows.Forms.Label lblCode;
        private System.Windows.Forms.Label lblToUser;
        private System.Windows.Forms.Label lblFromUser;
        private System.Windows.Forms.Button btnPrint;
        private System.Windows.Forms.Button btnExit;
        private System.Windows.Forms.Button btnPrintPreview;
        private System.Windows.Forms.PrintPreviewDialog printDocPreviewDialog;
    }
}