//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PfsenseVoucherMgr.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PfsenseVoucherMgr.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Bubbles_70x400 {
            get {
                object obj = ResourceManager.GetObject("Bubbles_70x400", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap mynetwork_places_22589 {
            get {
                object obj = ResourceManager.GetObject("mynetwork_places_22589", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection test successful..
        /// </summary>
        public static string RES_ID_CheckDb {
            get {
                return ResourceManager.GetString("RES_ID_CheckDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher code for:.
        /// </summary>
        public static string RES_ID_CodeFor {
            get {
                return ResourceManager.GetString("RES_ID_CodeFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated by:.
        /// </summary>
        public static string RES_ID_CodeGenBy {
            get {
                return ResourceManager.GetString("RES_ID_CodeGenBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language change will take full effect the next time you start the program..
        /// </summary>
        public static string RES_ID_CultureChange {
            get {
                return ResourceManager.GetString("RES_ID_CultureChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter min. 10 characters !.
        /// </summary>
        public static string RES_ID_MinChar {
            get {
                return ResourceManager.GetString("RES_ID_MinChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text contains not allowed strings !.
        /// </summary>
        public static string RES_ID_SqlWords {
            get {
                return ResourceManager.GetString("RES_ID_SqlWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  vouchers imported.
        /// </summary>
        public static string RES_ID_VImport {
            get {
                return ResourceManager.GetString("RES_ID_VImport", resourceCulture);
            }
        }
    }
}
